"""empty message

Revision ID: a91e74f1933a
Revises: d9a7a7b6dc23
Create Date: 2024-05-29 14:07:34.913019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a91e74f1933a'
down_revision = 'd9a7a7b6dc23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_drinks',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_drinks',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)

    # ### end Alembic commands ###
