"""empty message

Revision ID: c6087d64fa14
Revises: 
Create Date: 2024-05-10 15:46:14.966789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6087d64fa14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drinks',
    sa.Column('drink_id', sa.String(), nullable=False),
    sa.Column('drink_name', sa.String(length=1000), nullable=False),
    sa.Column('drink_price', sa.String(length=20), nullable=False),
    sa.Column('drink_ingredients', sa.String(length=5000), nullable=True),
    sa.Column('drink_instructions', sa.String(), nullable=True),
    sa.Column('drink_date_created', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('drink_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('order_date', sa.String(), nullable=False),
    sa.Column('order_total', sa.String(), nullable=False),
    sa.Column('order_payinfo', sa.String(), nullable=False),
    sa.Column('order_payexp', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=500), nullable=False),
    sa.Column('password', sa.String(length=1000), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_drink',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('drink_id', sa.String(), nullable=False),
    sa.Column('drink_qty', sa.String(), nullable=False),
    sa.Column('drink_name', sa.String(), nullable=False),
    sa.Column('drink_price', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.drink_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_drink')
    op.drop_table('user')
    op.drop_table('orders')
    op.drop_table('drinks')
    # ### end Alembic commands ###
