"""empty message

Revision ID: d9a7a7b6dc23
Revises: c6087d64fa14
Create Date: 2024-05-13 10:25:21.690067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a7a7b6dc23'
down_revision = 'c6087d64fa14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.alter_column('drink_qty',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.alter_column('drink_qty',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
